arm:
  kinematics_solver: pick_ik/PickIkKinematicsPlugin
  kinematics_solver_timeout: 0.05
  kinematics_solver_attempts: 3
  mode: global  # 'global' is better for far-away targets; use 'local' for small adjustments
  position_threshold: 0.001
  orientation_threshold: 0.01
  # The "Secret Sauce" for 5-DOF:
  # We tell it to care less about orientation if it can't find a perfect match
  orientation_scale: 0.5s